name: Deploy Static Site to S3

on:
  push:
    branches:
      - develop
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Use Node.js 22.15
        uses: actions/setup-node@v4
        with:
          node-version: '22.15.0'

      - name: Install dependencies
        run: npm ci

      - name: Build static site
        run: npm run build

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Determine bucket based on branch
        id: bucket
        run: |
          BRANCH_NAME="${GITHUB_REF##*/}"
          echo "Current branch: $BRANCH_NAME"
          if [[ "$GITHUB_REF" == "refs/heads/develop" ]]; then
            echo "bucket_name=${{ secrets.BUCKET_NAME_DEV }}" >> $GITHUB_OUTPUT
          elif [[ "$GITHUB_REF" == "refs/heads/main" ]]; then
            echo "bucket_name=${{ secrets.BUCKET_NAME_PROD }}" >> $GITHUB_OUTPUT
          else
            echo "Invalid branch for deployment"
            exit 1
          fi
      - name: Sync dist/ to S3
        run: |
          aws s3 sync dist/ s3://${{ steps.bucket.outputs.bucket_name }} --delete
      - name: Invalidar cache DEV
        if: github.ref_name == 'develop'
        run: aws cloudfront create-invalidation --distribution-id ${{ secrets.DISTRIBUTION_ID_DEV }} --paths "/*"

      - name: Invalidar cache PROD
        if: github.ref_name == 'main'
        run: aws cloudfront create-invalidation --distribution-id ${{ secrets.DISTRIBUTION_ID}} --paths "/*"

